Docker compose
COXIT-CO/RecruitFlowAI pull request #35
Opened 2023-10-23 15:37 UTC by rashboldb

### 🛠 Changes being made
This resolves issue https://github.com/COXIT-CO/RecruitFlowAI/issues/32

* Added docker compose 
* Added Grafana, Loki & Promtail services for comfort logging 
* Removed layer from Dockerfile where we copy .env, env provided via docker compose now

**Known issues:** 
This is not the best practice to expose direct access to the Docker daemon. Make sure you won't use malicious software alongside/inside the provided containers or use a more sophisticated approach for logs sharing.   

### 🧪 How was it tested? / Demo
Tested manually, after the services started visit localhost at port 3200 to access Grafana and enjoy your logs
### 📸 Screenshots

<img width="1424" alt="image" src="https://github.com/COXIT-CO/RecruitFlowAI/assets/8112226/fe8c5f5e-b6c0-4da0-8a3b-3fa71863033b">

### 🏎 Quality check

- []  Set base branch to main.
- [x]  Pull request is prepared: Added to sprint, added yourself as assignee, reviewers are added.
- [X]  PR is not very big (about 200 lines of change ideally).
- [x]  I have added comments to my code, particularly in hard-to-understand areas.
- [x]  Doesn't create any new FIXME or TODO comments. If not, please explain.
- [x]  Tested manually (explained the scenario, added screenshots)
- [x]  I have tested my changes locally before pushing them to this branch.
- [x]  I have updated the documentation accordingly.
- [x]  Followed best practice rules:https://google.github.io/styleguide/pyguide.html

2023-10-23 16:38 UTC, iramykytyn commented on logging_configs/grafana-datasources.yml
move the folder with scripts to `./scripts/loki` folder

2023-10-23 16:43 UTC, iramykytyn requested changes
Update readme how to start bot now with docker compose.

2023-10-24 11:22 UTC, iramykytyn reviewed
Could you record loom how to setup grafana so it's clear how to record logs though public access to IP? Now I can see grafana UI but I can't login https://www.loom.com/share/f7c0f1bd19ca4bcd9267974dddc0b98e.

It will be helpful to have that loom attached to readme with info how to view logs.

2023-10-24 11:24 UTC, iramykytyn commented on docker-compose.yml
probably configure some services to depend on others. For example to not start bot if Loki is not up yet. But think about it carefully if it makes sense to you.

2023-10-24 13:57 UTC, rashboldb commented on docker-compose.yml
not sure if we want to have this. I can imagine scenarios where we'd like to run bot and not to run Loki and vice versa. the only necessary dependency here is cloudflare tunnel container most likely.

2023-10-24 15:17 UTC, iramykytyn commented
https://www.loom.com/share/591ebf77515d49ea82a13ed4aa605c6b

2023-10-24 16:04 UTC, rashboldb commented
> https://www.loom.com/share/591ebf77515d49ea82a13ed4aa605c6b

Here I demonstrate that the logs being sent and we can access the fresh once. 
https://www.loom.com/share/d43e8b32eec8448d9c16d955ebdd66c6?sid=80a47f21-a801-4632-91dc-778615426091

It's not obvious rn, what's the reasons behind the failure in your case. Have to investigate more on the quesion, but it'll be hard to debug without being able to reproduce.

2023-10-25 11:44 UTC, iramykytyn approved these changes
looks good,  only fix conflicts

2023-10-27 10:47 UTC, merged